title: "Patricia KOTO"
description: "Data Analyst | Statisticienne | Économiste du développement"

# Image de profil
logo: /assets/img/photo.jpg

# Thème stable et visuel
theme: jekyll-theme-cayman

# Langue
lang: fr

# Options
show_downloads: false

# Réseaux (optionnel mais pro)
github:
  is_project_page: true

# SEO (optionnel)
plugins:
  - jekyll-seo-tag
